server:
  port: 8881

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mudabirhussain/config-repo
          #username: ${GITHUB_USERNAME}
          #password: ${GITHUB_PASSWORD}
          clone-on-start: true
      label: main

management:
  endpoints:
    web:
      exposure:
        include: "*"